<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>op3_football_l1</name>
  <version>0.1.0</version>
  <description>L1 ROS bridge for OP3 football stack</description>
  <maintainer email="robotis@todo.todo">robotis</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>robotis_controller_msgs</depend>
  <depend>op3_walking_module_msgs</depend>
  <depend>op3_football_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
